Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> Anyone know why this fails or how to fix it?
> In file included from /data0/jenkins/workspace/ci-repository/openbmc/smbios-mdr/include/mdrv2.hpp:19,
>                  from /data0/jenkins/workspace/ci-repository/openbmc/smbios-mdr/src/mdrv2_main.cpp:17:
> /data0/jenkins/workspace/ci-repository/openbmc/smbios-mdr/include/dimm.hpp:69:14: error: ‘uint32_t phosphor::smbios::Dimm::memorySizeInKB(uint32_t)’ marked ‘override’, but does not override
>    69 |     uint32_t memorySizeInKB(uint32_t value) override;
>       |

memorySizeInKB type was changed from uint32 to size: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/41870

Patch-set: 1
Reviewer: Gerrit User 1000900 <1000900@adbd0a64-1f21-4d83-b585-671fe73cb6e4>