clang-tidy: removed unused variable
Delete the unused variable to resolve -Wunused-variable under -Werror.
No functional changes.

Fixed below error
'''
../include/firmware_inventory.hpp:60:14: error: private field 'storage' is not used [-Werror,-Wunused-private-field]
   60 |     uint8_t* storage;
      |              ^
'''

Change-Id: Ia8e69e5399794c83a50261132cbfd37e0fa9ecd3
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>